### ISSUE TITLE
Cannot Find .env File

### ISSUE THREAD

**Issue by timscott** [zetachang/react-native-dotenv#3] opened 2016-12-23 17:26 UTC
When packaging, I'm getting this error, even though I have ```.env``` file in the root of the repo (```/Users/me/app/mobile/.env```).

```bash
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.module.exports.config (/Users/me/app/mobile/node_modules/dotenv/lib/main.js:30:37)
    at PluginPass.visitor.ImportDeclaration (/Users/me/app/mobile/node_modules/babel-plugin-dotenv/index.js:20:39)
    at newFn (/Users/me/app/mobile/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/me/app/mobile/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/me/app/mobile/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/me/app/mobile/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/me/app/mobile/node_modules/babel-traverse/lib/context.js:150:16) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env.development'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.module.exports.config (/Users/me/app/mobile/node_modules/dotenv/lib/main.js:30:37)
    at PluginPass.visitor.ImportDeclaration (/Users/me/app/mobile/node_modules/babel-plugin-dotenv/index.js:22:61)
    at newFn (/Users/me/app/mobile/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/me/app/mobile/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/me/app/mobile/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/me/app/mobile/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/me/app/mobile/node_modules/babel-traverse/lib/context.js:150:16)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env.development' }
```

**Comment by zetachang** [comment] 2016-12-24 06:49
I think I can reproduce the issue. Since the packager is not aware of the `.env` file you might added after the packager is launched, so a workaround is **edit the file importing `react-native-dotenv` again** (which will trigger the packager to recompile the file.)

Also would you mind providing more details like:

1. which version of react-native?
2. how you start the package? (e.g. `yarn start`)

**Comment by levity** [comment] 2017-01-04 00:51
I'm getting this error as well. When I dig into `node_modules/dotenv/lib/main.js`, I see a `fs.readFileSync` line which receives only '.env' as an argument. And `process.env.PWD` at that point is equal to the working directory of the packager (`node_modules/react-native/packager`), not the root directory of my project.

**Comment by levity** [comment] 2017-01-04 00:52
It works if I use `yarn start`! Thanks! Just started learning React Native and didn't know about that.

**Comment by zetachang** [comment] 2017-01-04 01:34
@levity what's the command you use when you get the error ?

**Comment by levity** [comment] 2017-01-04 01:37
I was using `[absolute path to project dir]/node_modules/react-native/packager/launchPackager.command`

**Comment by zetachang** [comment] 2017-01-09 07:11
This issue might be fixed in the latest version (0.0.3), tested against `yarn start` & `launchPackager.command`.

**Comment by dantman** [comment] 2017-01-17 00:02
There seems to be a big problem related to different (perfectly valid) ways of launching the packager.

If you run `react-native start` yourself the cwd is the root of your project.

If you run `react-native run-[android,ios]` and allow it to implicitly launch the packager, the cwd is `{package}/node_modules/react-native/packager`.

This seems to be a big issue where the cwd `babel-plugin-dotenv` relies on is not reliable.

**Comment by zetachang** [comment] 2017-01-17 00:18
@dantman , you are right, so I've changed the implementation to use the default way used by react-native to resolve project root. https://github.com/zetachang/react-native-dotenv/blob/master/index.js#L7

**Comment by zetachang** [comment] 2017-01-29 06:59
Closing for now, feel free to reopen if you still encounter the issue.

**Closed** 2017-01-29 06:58 UTC

**Comment by nvs2394** [comment] 2018-08-20 04:08
@zetachang thanks I resolved my issue
